# Generated by Django 4.1.4 on 2023-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YDoc",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("data", models.BinaryField()),
            ],
        ),
    ]
